name = "karaoke-roast-machine"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

# Workers AI binding
[ai]
binding = "AI"

# Durable Objects for user state/memory
[[durable_objects.bindings]]
name = "USER_STATE"
class_name = "UserState"

# Workflows for coordination (correct format)
[[workflows]]
name = "audio-processing-workflow"
binding = "AUDIO_WORKFLOW"
class_name = "AudioProcessingWorkflow"

# Migration for SQLite-backed Durable Objects
[[migrations]]
tag = "v1"
new_sqlite_classes = ["UserState"]